### ISSUE TITLE
ca.py - use on linux

### ISSUE THREAD

**Issue by lawreader** [b1tninja/misty#1]
Hello, 

I saw your feedback on CA's legislative website. Agree 100% their documentation is severely lacking and access to the statutes in a human readable format is not acceptable. I thank you for creating the ca.py script, however, I am having trouble using it in Linux. Any suggestions? Thanks

**Comment by lawreader** [comment]
specifically, after downloading the zip file of lob's and unzipping them, then when running the script, I get:


>  File "ca.py", line 44
>   """
>      ^

**Comment by b1tninja** [comment]
So I designed it for python3.6, that line looks like the beginning of the format string, was there an error message? I'll make some improvements to it today to make sure it runs nicely on Linux.

Note too you don't need to unzip the .zip files. I only have it tested/working against the [pubinfo_2021.zip](https://downloads.leginfo.legislature.ca.gov/pubinfo_2021.zip) currently. 

It seems like every other year there are codes published, at least in the more recent years. Again, bad documentation ha.

I'll also make it so that `ca.py` has its own `__main__` function so that it can be run separately from the stuff I was doing with text to speech.

If you haven't set up a virtual environment or installed the `requirements.txt` in particular, these docs kind of go over how to do that: https://docs.python.org/3/tutorial/venv.html (`virtualenv3 lawreader; cd lawreader; . bin/activate; pip3 install < requirements.txt` disclaimer: from memory)
- whoosh (_will be_ optional, for full text searching)
- html2text (needed to convert the HTML code to text, I suppose I could make this optional and have it display html).

I'll try to add some comments to the code too

**Comment by lawreader** [comment]
I appreciate your response. Thank you for your time.

**Comment by lawreader** [comment]
and the error was that it just crapped out at that line.. no more details were given..

**Comment by b1tninja** [comment]
So that line as it's written uses a new feature of [python 3.6](https://docs.python.org/3/whatsnew/3.6.html), [f-strings](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498). My guess is perhaps you are on an older version of python, maybe 3.4... I'll be making some changes to improve the backwards-compatibility to get it working for ya

**Comment by b1tninja** [comment]
Ok @lawreader when you get a chance please give the updated code a try. I pushed this commit just now https://github.com/b1tninja/misty/commit/d2b0cc599fbac3a7d1996a3f1d1ff088f1514359

**Comment by lawreader** [comment]
sorry to be such a python noob.. not my native language.. different but more clear error message:

```
 File "ca.py", line 31
SyntaxError: Non-ASCII character '\xe2' in file ca.py on line 31, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```

**Comment by b1tninja** [comment]
Ah ok. I think I know what caused that. I tried to include fancy utf-8 characters for "colorization". Fixed by removing that for now.  https://github.com/b1tninja/misty/commit/cf71080c52025ef6fcf65bee30ab008184cb6f88

**Comment by lawreader** [comment]
closer..

>  File "ca.py", line 252
>   def parse_datlobs(LOBS, *, CODES_TBL, LAW_TOC_TBL, LAW_SECTION_TBL, LAW_TOC_SECTIONS_TBL):
>                             ^
>SyntaxError: invalid syntax

Don't drive yourself crazy, trying to figure out the spaghetti mess of SQL data they provide. Absolutely no docs, left to figure this ish out.. They don't want to make it easy, do they..

Thanks for your help and time.

**Comment by lawreader** [comment]
im using:

`Python 2.7.17`

I should probably update anyway..

**Comment by b1tninja** [comment]
Unfortunately the migration for python2 system to python3 was kind of a pain in the ass for everyone, python experts included.  What system are you on? Maybe I could help you install python3. 

If you are able to update to python 3.4 or newer that is the oldest I've tested against. Most distros will let you have both a python2.x and a python3.x. The catch is which is symlinked to `python`. You can see which with `which python`. 

It's possible `python3` is already installed, just not used by default. I fixed the shebang in https://github.com/b1tninja/misty/commit/52aea4785d197c190fccda2ac997e2cadfd64547 which might just make it work, but go ahead and try running it with python3 like so: `python3 ca.py`

Glad there are other people interested in the issue. Would love to help you get it working

**Comment by b1tninja** [comment]
```
            d.update(CODE_HEADING=CODES_TBL[LAW_CODE],
                     DIVISION_HEADING=toc_tbl[LAW_CODE][DIVISION][None][None]['HEADING'],
                     CHAPTER_HEADING=toc_tbl[LAW_CODE][DIVISION][CHAPTER][None]['HEADING'],
                     ARTICLE_HEADING=toc_tbl[LAW_CODE][DIVISION][CHAPTER][ARTICLE]['HEADING'],
                     ARTICLE_HISTORY=toc_tbl[LAW_CODE][DIVISION][CHAPTER][ARTICLE]['HISTORY_NOTE'],
                     LAW=LOB,
                     SECTION_TITLE=code_section_titles[LAW_CODE].get(SECTION_NUM, {}).get('TITLE'),
                     SECTION_HISTORY=HISTORY)
```
Is almost sort of a description of their SQL tables, think of those as sort of (SELECT HISTORY_NOTE, HEADING FROM idk JOIN on LAW_CODE= code AND DIVISION= division AND CHAPTER= chapter and ARTICLE = article) that was the "tricky" part of their mess of LOBs =)

**Comment by lawreader** [comment]
AHA! Very good sir! I do have python3 available, ver Python 3.6.9. I can run that with no errors! Working on it now. Thanks again!

**Comment by lawreader** [comment]
fantastic, excellent work! thank you very much!

Are you opposed to commercial use of your script?

**Comment by lawreader** [comment]
WOW, beautiful script! Can I use this in a mildly commercial use?

**Comment by b1tninja** [comment]
> Are you opposed to commercial use of your script?

Not at all, just cite it somehow, doesn't need to be displayed or anything, readme or a comment would be fine. =) Maybe I could help develop it ;D

https://leginfo.legislature.ca.gov/faces/feedbackDetail.xhtml?primaryFeedbackId=prim1614216471200 would be perfect =X

**Comment by lawreader** [comment]
Absolutely! will do. Thanks again
